/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
  const { nodes, materials } = useGLTF('./models/office.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Deskmat.geometry}
        material={materials.Black}
        position={[1.289, 2.915, -2.962]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2}
      />
      <group position={[2.083, 1.042, -1.005]} rotation={[0, -0.873, 0]} scale={2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials['Black.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials.GreyMetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_2.geometry}
          material={materials['Rubber.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor_ultrawide.geometry}
        material={materials['Black.003']}
        position={[1.289, 2.909, -4.373]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monitor.geometry}
        material={materials['Black.004']}
        position={[-1.097, 3.655, -3.692]}
        rotation={[0, -0.646, 0]}
        scale={2}
      />
      <group position={[1.289, 2.843, -3.39]} rotation={[0, Math.PI / 2, 0]} scale={2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials['Black.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials['White.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials['Rubber.002']}
        />
      </group>
      <group position={[1.241, 2.962, -2.846]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 2, 2.5]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials['Grey.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials['Black.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_2.geometry}
          material={materials['GreyLight.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_3.geometry}
          material={materials['White.002']}
        />
      </group>
      <group position={[2.459, 2.965, -2.884]} rotation={[0, -Math.PI / 2, 0]} scale={2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials['GreyLight.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials['Black.011']}
        />
      </group>
      <group position={[5.967, 1.184, -2.821]} scale={2}>
        <group position={[0, -0.097, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_7_1.geometry}
            material={materials['Black.012']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_7_2.geometry}
            material={materials.Brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Houseplant_7_3.geometry}
            material={materials.Plant_Green}
          />
        </group>
      </group>
      <group position={[-2.352, 5.766, -4.58]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry}
          material={materials.lambert3SG}
        />
      </group>
      <group position={[-3.43, 6.35, -3.88]} scale={3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Books.geometry}
          material={materials['Material.003']}
          position={[0.088, -0.001, -0.197]}
          scale={2}
        />
      </group>
      <group position={[-4.197, 0.99, 5.074]} scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Standing_lamp_01_Circle003-Mesh'].geometry}
          material={materials['795548']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Standing_lamp_01_Circle003-Mesh_1'].geometry}
          material={materials.DD9944}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Standing_lamp_01_Circle003-Mesh_2'].geometry}
          material={materials['455A64']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Standing_lamp_01_Circle003-Mesh_3'].geometry}
          material={materials.FFEB3B}
        />
      </group>
      <group position={[2.742, 2.96, -4.378]} scale={2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials['Black.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials['Grey.004']}
        />
      </group>
      <group position={[2.358, 1.025, 3.821]} rotation={[0, Math.PI / 2, 0]} scale={2}>
        <group position={[0.256, 0, -0.616]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Carpet_1_1.geometry}
            material={materials.DarkRed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Carpet_1_2.geometry}
            material={materials.LightOrange}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Wall}
        position={[0, 6, -6]}
        scale={[7, 5, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Floor}
        scale={[7, 1, 7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Wall}
        position={[-6, 6, 1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[6, 5, 1]}
      />
    </group>
  )
}

useGLTF.preload('./models/office.glb')